version: '3'
services:
  cm-back:
    build: ./
    container_name: cm-back
    ports:
      - 1337:1337
    depends_on:
      - cm-mongodb
  cm-mongodb:
    restart: unless-stopped
    image: mongo:6-jammy
    container_name: cm-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
  cm-nginx:
    restart: unless-stopped
    image: jonasal/nginx-certbot
    container_name: cm-nginx
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: luchcko.a@gmail.com
      DOMAIN: test-project.site
    volumes:
      - ./nginx/conf.d:/etc/nginx/user_conf.d:ro
      - ../trip-house-frontend/dist:/usr/share/app
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - cm-back
  cm-minio:
    restart: unless-stopped
    image: quay.io/minio/minio
    container_name: cm-minio
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: luchko
      MINIO_ROOT_PASSWORD: password
      MINIO_DOMAIN: s3.test-project.site
      MINIO_BROWSER_REDIRECT_URL: https://minio.test-project.site
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9090"

volumes:
  mongodb_data:
  letsencrypt:

networks:
  default:
    name: cm
